mysql:
  restart: always
  image: mysql:5.5
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=fbctf
    - MYSQL_USER=fbctf
    - MYSQL_PASSWORD=fbctf
memcached:
  restart: always
  image: memcached
fbctf:
  restart: always
  image: fbctf
  links:
    - memcached:memcached
    - mysql:mysql
  environment:
    - MYSQL_HOST=mysql
    - MYSQL_PORT=3306
    - MYSQL_DATABASE=fbctf
    - MYSQL_USER=fbctf
    - MYSQL_PASSWORD=fbctf
    - MEMCACHED_PORT=11211
    - SSL_SELF_SIGNED=true
  ports:
    - "80:80"
    - "443:443"
